language: java
jdk:
- oraclejdk8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
- mvn install -DskipTests=true
script:
- mvn test -Dmaven.javadoc.skip=true
notifications:
  slack: s31a:zh1UThYC3YUumqVzaPrPwkRj