language: java
jdk:
- oraclejdk8
# setup jobs.
env:
  - USE_FRAMEBUFFER=true
  - USE_FRAMEBUFFER=false _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
# run on xvfb screen.
before_install:
  - if [ $USE_FRAMEBUFFER = "true" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi
install:
- mvn install -DskipTests=true
script:
- mvn test -Dmaven.javadoc.skip=true
notifications:
  slack: s31a:zh1UThYC3YUumqVzaPrPwkRj